name: ava_dashboard_env
channels:
  - https://repo.anaconda.com/pkgs/snowflake
dependencies:
  - python=3.9
  - snowflake-snowpark-python
  - snowflake-connector-python
  - pandas
  - plotly
  - pyvis
  - streamlit
  - toml